### ISSUE TITLE
DahuaSunriseSunset.exe does not work after daylight savings

### ISSUE THREAD

**Issue by hndrk** [bp2008/DahuaSunriseSunset#8]
Hello, 

DahuaSunriseSunset.exe does not work after daylight savings -- it did not change the profile of the cameras as it normally would.
When the "View rise/set" is clicked, the message box says "label1" instead of the expected output.
Note: Sunrise Offset Hours are 0, and my Sunset Offset Hours are -0.1.

Error log is as follows:
27/09/2021 12:06:19 PM	DahuaSunriseSunset 1.8.0.0 Service Manager Startup
27/09/2021 12:09:05 PM	Application_ThreadException
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Time offsets cannot be greater than 12 or less than -12.
   at CoordinateSharp.Coordinate.set_Offset(Double value)
   at DahuaSunriseSunset.SunHelper.Calc(Double lat, Double lon, DateTime& nextRise, DateTime& nextSet, Boolean& timeZoneAndLongitudeAreCompatible, Double sunriseOffsetHours, Double sunsetOffsetHours)
   at DahuaSunriseSunset.ViewNextSunriseSunset.ViewNextSunriseSunset_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by bp2008** [comment]
What time zone is your computer configured for?

**Comment by bp2008** [comment]
Assuming your UTC offset is above +12, then the problem is a bug in the CoordinateSharp library used by this project.  I have filed an issue with them.  https://github.com/Tronald/CoordinateSharp/issues/193

It looks like it is probably straightforward to patch their library to fix this, but I am going to see if their maintainer responds quickly, maybe I won't have to do it myself.

**Comment by Tronald** [comment]
@bp2008 Thanks for bringing this to my attention. The IDL extensions around those areas was not considered for local time conversion. Thankfully CoordinateSharp appears to only require a simple validation adjustment to allow for +14 offset.

Will get this fixed ASAP.

**Comment by Tronald** [comment]
Patch is built for CoordinateSharp, I just need to button up a few things before I push it (should be on Nuget in the next hour). I want to note a few odd things I noticed about this region though. Most webservices seem to exhibit the same behavior (with +12 UTC offset max).

For example Time and Date says LINT is +14 : https://www.timeanddate.com/time/zones/lint
But their sun times appear in +12:  https://www.timeanddate.com/sun/@4030885

NOAA however seems to exhibit the correct behavior when setting +14 UTC (notice the 2 hour difference in reported time): https://gml.noaa.gov/grad/solcalc/

![image](https://user-images.githubusercontent.com/24424871/134956338-142e83db-b1b5-44f7-ad2f-fe49a105c63f.png)

I bring this up, because testing in this region may require additional research. The math in CoordinateSharp is correct though from testing (adding 14 hours from UTC for solar/lunar calculation).

CoordinateSharp Reported Time in Regions
```
SUNSET: 9/28/2021 8:21:52 PM
SUNRISE: 9/28/2021 8:15:35 AM
```

**Comment by Tronald** [comment]
Patch pushed to [Nuget with v2.12.1.1 ](https://www.nuget.org/packages/CoordinateSharp/). Should fix the issue, but let me know if you run into any issues @bp2008 when updating your repo.

**Comment by bp2008** [comment]
Thanks @Tronald for the very quick work!

@hndrk please try [DahuaSunriseSunset 1.9](https://github.com/bp2008/DahuaSunriseSunset/releases) and let us know if the issue is resolved!

**Comment by hndrk** [comment]
@bp2008 you were correct in assuming my UTC offset is above +12 (during daylight savings).

I've been through a couple of sunrise and sunsets with v1.9 -- the profiles switch properly and everything seems to be working fine.

Thank you both @Tronald and @bp2008!
